### ISSUE TITLE
uninitialized constant RspecApiDocumentation::Writers::JsonWriter (NameError)

### ISSUE THREAD

**Issue by rlgreen91** [zipmark/rspec_api_documentation#382] opened 2018-07-02 17:23 UTC
System info:
* Ruby 2.5.1
* Rails 5.2.0
* Rspec 3.7.0
* RspecApiDocumentation 5.1.0

I have my specs set up in `spec/acceptance`, as required.  When I run `bundle exec rake docs:generate`, I get the following error:

```
/Users/rachel/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant': uninitialized constant RspecApiDocumentation::Writers::JsonWriter (NameError)
```

My configuration is set up as described in `rails_helper.rb`.  This only occurs with trying to output as JSON - outputting as a different format, like HTML, works fine.  I'm guessing it's not resolving the names correctly - it's looking for JsonWriter, not JSONWriter, as listed in the gem.

**Comment by jakehow** [comment] 2018-07-05 18:16
This is related to PR #359

**Comment by rprieto** [comment] 2018-07-13 08:34
Note: it also affects the `:open_api` format (since it's JSON based).

**Comment by obromios** [comment] 2018-07-30 04:01
I am seeing this when cloning the repository and change
```
#example/spec/acceptance_helper.rb
..
config.format = [:open_api]
...

```
to ```config.format=[:json]```

**Comment by jclif** [comment] 2018-08-29 02:09
Experiencing this issue as well.

**Comment by xtofthomas** [comment] 2018-08-29 07:59
rspec_api_documentation/api_documentation.rb:35:in `const_get': uninitialized constant RspecApiDocumentation::Writers::JsonWriter (NameError)

The same for me too !

**Comment by vladimirbazhanov** [comment] 2018-08-31 10:25
I see the same issue too

**Comment by jakehow** [comment] 2018-08-31 14:39
I linked to the issue that probably created this above.  If you are experiencing this check that out and see if it helps.  My guess is there was some change between Ruby/Rails versions that flipped how this constant was interpreted and we will need to handle it with a check or alias the constant.

If someone experiencing this can put up a sample app with the problem and pinned to the versions they are experiencing it with via a .ruby-version and Gemfile.lock maybe we can narrow it down.

**Comment by bf4** [comment] 2018-09-02 15:29
solution: change `config.format = :json` to `config.format = :JSON`.

**Comment by roramirez** [comment] 2018-09-04 13:13
as @bf4  mention before this fix the issue for me.

Here is my  [Gemfile.lock](https://github.com/zipmark/rspec_api_documentation/files/2348742/Gemfile_lock.txt)

**Comment by oestrich** [comment] 2018-09-04 15:42
I merged #399, can everyone update to the git master branch and let me know if it solves your problems? If it does, I'll do a new release on rubygems.

**Comment by incubus** [comment] 2018-09-11 11:40
It works, thanks!

**Comment by dikond** [comment] 2018-09-20 16:29
I can confirm that it works on master.

**Comment by oestrich** [comment] 2018-10-03 17:28
6.1.0 is out and has #399 in it.

**Closed by oestrich** 2018-10-03 17:28 UTC
