### ISSUE TITLE
Formatter fails -- No such file or directory

### ISSUE THREAD

**Issue by dustineichler** [zipmark/rspec_api_documentation#143] opened 2014-07-15 03:54 UTC
Installed the gem. I'm using Apitome. I'm not able to run the initial rake task to generate the docs I need. Looks like it can't find one of the template files on this line 10 of general_markup_writer.rb

``` ruby
module RspecApiDocumentation
  module Writers
    # Base class for writers that write HTML
    class GeneralMarkupWriter < Writer
      INDEX_FILE_NAME = 'index'

      # Write out the generated documentation
      def write
        File.open(configuration.docs_dir.join(index_file_name + '.' + extension), "w+") do |f|
          f.write markup_index_class.new(index, configuration).render
        end

        index.examples.each do |example|
          markup_example = markup_example_class.new(example, configuration)
          FileUtils.mkdir_p(configuration.docs_dir.join(markup_example.dirname))

          File.open(configuration.docs_dir.join(markup_example.dirname, markup_example.filename), "w+") do |f|
            f.write markup_example.render
          end
        end
      end

      def index_file_name
        INDEX_FILE_NAME
      end

      def extension
        raise 'Parent class. This method should not be called.'
      end
    end
  end
end
```

Trace

``` bash
/Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/mustache-0.99.5/lib/mustache/settings.rb:155:in `read': No such file or directory - /Users/ME/Documents/Projects/Client-Work/anthem.com/inside of the gem/rspec_api_documentation/html_index.mustache (Errno::ENOENT)
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/mustache-0.99.5/lib/mustache/settings.rb:155:in `template'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/mustache-0.99.5/lib/mustache.rb:108:in `render'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec_api_documentation-4.0.0/lib/rspec_api_documentation/writers/general_markup_writer.rb:10:in `block in write'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec_api_documentation-4.0.0/lib/rspec_api_documentation/writers/general_markup_writer.rb:9:in `open'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec_api_documentation-4.0.0/lib/rspec_api_documentation/writers/general_markup_writer.rb:9:in `write'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec_api_documentation-4.0.0/lib/rspec_api_documentation/writers/writer.rb:13:in `write'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec_api_documentation-4.0.0/lib/rspec_api_documentation/api_documentation.rb:27:in `block in write'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec_api_documentation-4.0.0/lib/rspec_api_documentation/api_documentation.rb:26:in `each'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec_api_documentation-4.0.0/lib/rspec_api_documentation/api_documentation.rb:26:in `write'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec_api_documentation-4.0.0/lib/rspec_api_documentation/api_formatter.rb:38:in `each'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec_api_documentation-4.0.0/lib/rspec_api_documentation/api_formatter.rb:38:in `stop'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib/rspec/core/reporter.rb:137:in `block in notify'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib/rspec/core/reporter.rb:136:in `each'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib/rspec/core/reporter.rb:136:in `notify'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib/rspec/core/reporter.rb:131:in `stop'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib/rspec/core/reporter.rb:113:in `finish'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib/rspec/core/reporter.rb:56:in `report'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib/rspec/core/runner.rb:108:in `run_specs'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib/rspec/core/runner.rb:86:in `run'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib/rspec/core/runner.rb:70:in `run'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib/rspec/core/runner.rb:38:in `invoke'
    from /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/exe/rspec:4:in `<main>'
/Users/ME/.rvm/rubies/ruby-2.0.0-p451/bin/ruby -I/Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/lib:/Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-support-3.0.0/lib -S /Users/ME/.rvm/gems/ruby-2.0.0-p451@anthem.com/gems/rspec-core-3.0.1/exe/rspec --format RspecApiDocumentation::ApiFormatter failed
You have new mail in /var/mail/ME
```

**Comment by oestrich** [comment] 2015-12-17 19:09
Closing due to age.

**Comment by kurko** [comment] 2017-05-15 19:46
Still happening. I figured out that it happens when having multiple groups. In the code below, when I uncomment the `public` group definition, I get this error.

```ruby
RspecApiDocumentation.configure do |config|
  config.format = [:api_blueprint]
  config.filter = :private
  config.docs_dir = Rails.root.join("doc", "api", "private")

  #config.define_group :public do |c|
  #  c.format = [:api_blueprint]
  #  c.filter = :public
  #  c.docs_dir = Rails.root.join("doc", "api")
  #end
end
```

```
/Users/kurko/project_name/vendor/gems/rspec_api_documentation/lib/rspec_api_documentation/writers/general_markup_writer.rb:10:in `initialize': No such file or directory @ rb_sysopen - /Users/kurko/project_name/doc/api/private/index.apib (Errno::ENOENT)
        from /Users/kurko/project_name/vendor/gems/rspec_api_documentation/lib/rspec_api_documentation/writers/general_markup_writer.rb:10:in `open'
        from /Users/kurko/project_name/vendor/gems/rspec_api_documentation/lib/rspec_api_documentation/writers/general_markup_writer.rb:10:in `write'
        from /Users/kurko/project_name/vendor/gems/rspec_api_documentation/lib/rspec_api_documentation/writers/writer.rb:13:in `write'
        from /Users/kurko/project_name/vendor/gems/rspec_api_documentation/lib/rspec_api_documentation/api_documentation.rb:27:in `block in write'
        from /Users/kurko/project_name/vendor/gems/rspec_api_documentation/lib/rspec_api_documentation/api_documentation.rb:26:in `each'
        from /Users/kurko/project_name/vendor/gems/rspec_api_documentation/lib/rspec_api_documentation/api_documentation.rb:26:in `write'
        from /Users/kurko/project_name/vendor/gems/rspec_api_documentation/lib/rspec_api_documentation/api_formatter.rb:38:in `each'
        from /Users/kurko/project_name/vendor/gems/rspec_api_documentation/lib/rspec_api_documentation/api_formatter.rb:38:in `stop'
```

It happens even though I define the group separately. I'm still investigating.

**Comment by oestrich** [comment] 2017-05-15 19:48
I think the issue is related to having the sub group be above the main group. As part of the generation each group will `rm` their folder. Can you make the bottom group have `doc/api/public` and see what happens?

**Comment by kurko** [comment] 2017-05-15 19:57
@oestrich yes, precisely that. It deletes all folders in the beginning of the process. The solution is simple and if you give me a thumbs up I will open a PR:

```patch
      INDEX_FILE_NAME = 'index'

      # Write out the generated documentation
      def write
        if render_options.fetch(:index, true)
+         FileUtils.mkdir_p(configuration.docs_dir)
          File.open(configuration.docs_dir.join(index_file_name + '.' + extension), "w+") do |f|
            f.write markup_index_class.new(index, configuration).render
          end
        end

        if render_options.fetch(:examples, true)
          index.examples.each do |example|
            markup_example = markup_example_class.new(example, configuration)
            FileUtils.mkdir_p(configuration.docs_dir.join(markup_example.dirname))

            File.open(configuration.docs_dir.join(markup_example.dirname, markup_example.filename), "w+") do |f|
              f.write markup_example.render
            end
          end
        end
      end
```

**Comment by oestrich** [comment] 2017-06-08 13:50
Closing due to age.

**Closed by oestrich** 2017-06-08 13:50 UTC

**Comment by kurko** [comment] 2017-06-13 14:17
> The solution is simple and if you give me a **thumb up** I will open a PR:

**Comment by oestrich** [comment] 2017-06-13 14:32
Sorry about that, I was just looking at the age of the initial issue when I went on a closing spree last week. 👍 to your PR.
